[package]
name = "torch2424/wasmerboy"
version = "0.1.1"
description = "Game Boy / Game Boy Color Emulator Library, ðŸŽ®written for WebAssembly using AssemblyScript. ðŸš€Built for Wasmer using the Experimental I/O Devices!"
license = "GPL-3.0"
repository = "https://github.com/torch2424/wasmboy"
wasmer-extra-flags = "--enable-experimental-io-devices"
readme = "./README.md"

[[module]]
name = "wasmerboy"
source = "dist/wasmerboy.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.0.0-unstable"

[[command]]
name = "wasmerboy"
module = "wasmerboy"
